#ifndef SERVER_CONFIG_H_INCLUDED
#define SERVER_CONFIG_H_INCLUDED

#define SERVER_PIPE_NAME "server_pipe"
#define SERVER_INFO_FILE_PATH "server.info"
#define SERVER_MAX_CLIENTS 64

#define STRING_MAX_SIZE 64 

#define SERVER_MENU_WIDTH 32

#endif
